name: Deploy Tagged Release
on:
  release:
    types:
      - released
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
jobs:
  update-components:
    runs-on: ubuntu-latest
    steps:
      - uses: cluebotng/ci-update-component-ref@8e4650ab6aa94f2c4b08a1518e798a6e68e4bd44
        with:
          tool: 'cluebot3'
          component: 'cluebot3'
          ref: '${{ inputs.ref || github.ref }}'
          gh_app_key: '${{ secrets.CI_COMPONENT_CONFIGS_APP_KEY }}'
